spring:
  profiles:
    active: integration
  data:
    mongodb:
      uuid-representation: standard
      uri: mongodb://admin:admin@localhost:27017/lotto-web   # mongodb://[username:password@]host1[:port1]/[database-name]
      host: localhost
  cache:
    redis:
      time-to-live: 60

lotto:
  input:
    minNumber: 1
    maxNumber: 99
    numberCount: 6
  winning:
    minWinNumber: ${lotto.input.minNumber}
    maxWinNumber: ${lotto.input.maxNumber}
    winNumberCount: ${lotto.input.numberCount}
  time:
    drawDayOfWeek: SATURDAY
    drawHour: "12:00:00"
    expirationInDays: 930
  checker:
    matchedNumbersToWin: 3