spring:
  profiles:
   active: production
  data:
    mongodb:
      uuid-representation: standard
      uri: mongodb://admin:admin@localhost:27017/lotto-web   # mongodb://[username:password@]host1[:port1]/[database-name]
      host: localhost
  cache:
    redis:
      time-to-live: 60  # minutes of ttl for cached item

lotto:
  input:
    minNumber: 1
    maxNumber: 99
    numberCount: 6
  time:
    drawDayOfWeek: 6
    drawHour: 12
    drawMinutes: 0
    drawSeconds: 0
    drawTime: "${lotto.time.drawHour}:${lotto.time.drawMinutes}:${lotto.time.drawSeconds}"
    expirationInDays: 930
  checker:
    #lotteryRunOccurrence: "${lotto.time.drawSeconds} ${lotto.time.drawMinutes} ${lotto.time.drawHour} * * ${lotto.time.drawDayOfWeek}"
    lotteryRunOccurrence: "*/2 * * * * *"
    matchedNumbersToWin: 3
